### PR TITLE
Update info.plist

### PR DESCRIPTION
**Pull request by Haseong**
support 10.10

### CODE REVIEW

**Comment by surrealroad** [comment]
Can you provide some more information on what was changed? There are >1000 changes and github won't show them to me.

**Comment by just3ws** [comment]
Howdy. It looks like it's just that the modified date was changed (probably by the AppleScript tool).

The only change was to `info.plist` line 482.

```
 -- if (osver does not start with "10.6" and osver does not start with "10.7" and osver does not start with "10.8") then set showReminders to false
```

This is the delta of the change when I turned off the "Date modified" check.
alfred-reminders_and_alfred-reminders-haseong_-_deltopia_deltawalker

@Haseong please use `git add -p` then only add the relevant line when submitting a PR. :+1: 

@surrealroad It's probably fair to add the relevant line if you think it's good then just mention it was from @Haseong I can submit a PR if this is something you'd prefer.

**Comment by just3ws** [comment]
Wow, trying to update that file and only commit the one change *is* super-annoying. AppleScript has some weird line ending insanity that Git doesn't get along with and I can't really dig into now.

@surrealroad All the the commit did was comment out the one check (if I am understanding what `--` means in AppleScript). Maybe there's a cleaner way but I'm not fluent in AppleScript. :/

**Comment by surrealroad** [comment]
ok then, no, that code is in place for a reason:

> Note: OS 10.9 Onwards
>  
> This workflow currently operates in a "write-only" mode in OS 10.9 or later.
> Due to an issue with OS 10.9 (and likely 10.10), I have removed some of the functionality– specifically the ability to view current reminders within Alfred. You can still use all the commands for adding new reminders, and in the event that the issue is fixed, I will restore full functionality. Read on if you want more details on why this is.
>  
> When using this workflow with 10.9+, performance is extremely slow (14x slower than 10.8) due to an apparent bug in osascript (which may affect other Alfred workflows too, or might just be limited to accessing Reminder data). This means that fetching data from Reminders is taking around a minute or so per reminder. This is a reproducible bug with AppleScript that has nothing to do with Alfred or this workflow, which I have logged with Apple as of October 7 (#15163843), but has not yet been addressed (and as with other bugs, may never be).
>  
> The workflow is designed to use a caching process to store current reminders (as trying to access them directly on any OS version is somewhat slow), but even this can result in prolonged CPU spikes while the cache is built in 10.9+, as well as general unresponsiveness of Reminders.
>  
> This is probably the best I can do for now until the bug gets fixed (which might never happen). I am genuinely sorry about this, and if I can figure out a way around it, I will do so, but ultimately the workflow has to communicate with Reminders via AppleScript to some extent.

**Pull request closed without merging**
